name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['16']
    name: Node ${{ matrix.node }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - name: Upgrade yarn
        run: yarn install
      - name: Install
        run: yarn
      - name: Lint
        run: yarn run lint
      - name: Build
        run: yarn run build
      - name: Markdownlint
        run: yarn run markdownlint
      - name: Test
        run: yarn test
